name 'tctest'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures tctest'
long_description 'Installs/Configures tctest'
version '0.3.2'

depends 'apt', '~> 2.6.1'
depends 'mysql2_chef_gem', '~> 1.0.1'
depends 'mysql', '~> 6.1.0'
depends 'database', '~> 4.0.3'
depends 'poise-python', '~> 1.0.0'
depends 'ssh_known_hosts', '~> 2.0.0'
depends 'nginx-proxy', '~> 0.2.1'
